import { useQuery } from "@tanstack/react-query";

/**
 * One entry per placeholder .glb, as written by scripts/convert-placeholders.mjs
 * into apps/web/public/models/placeholders/manifest.json. Static asset, not an
 * API resource — the manifest and the .glb files are generated by the same
 * script, so they can't drift apart.
 */
export interface PlaceholderModel {
  group: string;
  name: string;
  url: string;
  clips: string[];
  height: number | null;
}

export function usePlaceholderModels() {
  return useQuery({
    queryKey: ["placeholder-models", "manifest"],
    staleTime: Infinity,
    queryFn: async () => {
      const res = await fetch("/models/placeholders/manifest.json");
      if (!res.ok) throw new Error(`manifest.json: HTTP ${res.status}`);
      return (await res.json()) as PlaceholderModel[];
    },
  });
}
